### ISSUE TITLE
Reproduce SSP results

### ISSUE THREAD

**Issue by panday1995** [JGCRI/pygcam#20]
Hi. I am trying to reproduce the SSP results using pygcam. Currently, I am using 
`pygcam 1.8`
`gcam 4.4`
`python 3.7`

I found there are SSP input files in the `../input/xml` file. Although I've read the pygcam doc for several times, I still have no idea how to configure those SSP files. Should I just change all the things in the `configureation_ref.xml` file to ssp files? For example, changing 
`<Value name = "socioeconomics">../input/gcam-data-system/xml/socioeconomics-xml/socioeconomics_gSSP2.xml</Value>` 
into 
`<Value name = "socioeconomics">../input/gcam-data-system/xml/socioeconomics-xml/socioeconomics_SSP1.xml</Value>`

**Comment by rjplevin** [comment]
Have you used GCAM before or are you learning how to use it and pygcam at the same time? Both have fairly steep learning curves. I highly recommend working a bit with GCAM directly first to gain an understanding of how to use it so that the features of pygcam will make sense.

**Comment by panday1995** [comment]
Thans a lot, Sir! I have bare knowledge in GCAM, but is more familiar with python so I started directly with pygcam. Seems GCAM is much easier to understand for a beginner.
