### ISSUE TITLE
Error while running gt run in GCAM 6.0

### ISSUE THREAD

**Issue by psadavarte** [JGCRI/pygcam#43]
Hi Richard

I'm new to gcam and I plan to use python for running and analyzing the model.  I successfully installed pygcam and used the command _gt init_. Later following the [initializing and configuring webpage](https://pygcam.readthedocs.io/en/master/initialize.html), I used _gt run_ which gave me error, shown below. Just for your information, I was trying to run the reference case scenario and I use mac.

==========================================================
(base) % gt run
INFO pygcam.project: [base, 1, setup] @setup -b "base" -g "group" -S "base" -w "~/gcam/gcam-v6.0-Mac-Release-Package/sandboxes/testrun/base" -p 2050 -y 2015-2050
INFO pygcam.scenarioSetup: Setting up GCAM workspace '~/gcam/gcam-v6.0-Mac-Release-Package/sandboxes/testrun/Workspace' for GCAM 6.0
INFO pygcam.scenarioSetup: Setting up sandbox '~/gcam/gcam-v6.0-Mac-Release-Package/sandboxes/testrun/base'
INFO pygcam.xmlEditor: Generating local-xml for scenario base
INFO pygcam.xmlEditor: No XML files to copy in ~/gcam/gcam-v6.0-Mac-Release-Package/projects/testrun/xmlsrc/base
INFO pygcam.xmlEditor: Copy ~/gcam/gcam-v6.0-Mac-Release-Package/exe/configuration_ref.xml
      to ~/gcam/gcam-v6.0-Mac-Release-Package/sandboxes/testrun/Workspace/local-xml/base/config.xml
INFO pygcam.xmlEditor: Writing '~/gcam/gcam-v6.0-Mac-Release-Package/sandboxes/testrun/Workspace/local-xml/base/config.xml'
INFO pygcam.xmlEditor: Generating dyn-xml for scenario base
gt failed: Refusing to delete ~/gcam/gcam-v6.0-Mac-Release-Package/sandboxes/testrun/base/dyn-xml/base, which is part of the reference workspace
==========================================================

Can you please help me figure out how to address this issue?

**Comment by rjplevin** [comment]
> gt failed: Refusing to delete ~/gcam/gcam-v6.0-Mac-Release-Package/sandboxes/testrun/base/dyn-xml/base, which is part of the reference workspace
> 

It looks like you chose to place your sandboxes inside the release package. The tool won't let you do that since you might overwrite parts of GCAM.

Rerun "gt init" and put your sandboxes somewhere else, e.g., ~/gcam/sandboxes

-Rich

**Comment by rjplevin** [comment]
BTW, I always advise folks new to GCAM to work with the model directly at first. Pygcam is fairly complicated; GCAM is much more so. Pygcam will make much more sense after you've become comfortable with GCAM.

**Comment by psadavarte** [comment]
Thank you so much for getting back on my query and for your suggestion on GCAM and Pygcam. Appreciate it.

**Comment by psadavarte** [comment]
I was able to run the model with the default configuration_ref file, after implementing your suggestion on sandboxes.
